### ISSUE TITLE
Cannot use svelte-loadable it in sapper

### ISSUE THREAD

**Issue by sebastianconcept** [kaisermann/svelte-loadable#17]
```
/...../node_modules/svelte-loadable/Loadable.svelte:1
(function (exports, require, module, __filename, __dirname) { <script context="module">
                                                              ^

SyntaxError: Unexpected token <
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
> Server crashed
```

```
Node v10.15.1
    "sapper": "^0.27.0",
    "svelte": "^3.12.1",
    "svelte-loader": "^2.13.6"
```

**Comment by CaptainN** [comment]
I think this is a config issue in either rollup or webpack. Check out [this readme section for using external packages](https://github.com/sveltejs/sapper-template/blob/master/README.md#using-external-components).

**Comment by kaisermann** [comment]
Yeah 🕺 nothing to do with `svelte-loadable`. Closing it 😁

**Comment by sandrina-p** [comment]
Hum @kaisermann what was the fix? I'm having the same issue.

**Comment by sandrina-p** [comment]
Figured it out! This package isn't needed with Sapper, [Sapper supports dynamic components out of the box](https://sapper.svelte.dev/docs/#Making_a_component_SSR_compatible).

```js
<script>
  import { onMount } from 'svelte';

  let MyComponent;

  onMount(async () => {
    const module = await import('my-non-ssr-component');
    MyComponent = module.default;
  });
</script>

<svelte:component this={MyComponent} foo="bar"/>
```

**Comment by kaisermann** [comment]
@sandrina-p They can actually work together. `svelte-loadable` only wraps and add some functionalities for loading dynamic components, it has nothing to do with how the dynamic import will be understood by a bundler/browser 😁 . You can rewrite that example with `svelte-loadable` in the following way:

```svelte
<script>
  import Loadable from 'svelte-loadable'
</script>

<Loadable loader={() => import('my-non-ssr-component')} foo="bar"/>
```

**Comment by sandrina-p** [comment]
@kaisermann I tried that but it didn't work, I had the same error as @sebastianconcept :/

**Comment by kaisermann** [comment]
@sandrina-p That was quick 😆 Would you be able to share a simple repro with the issue happening? It's probably a config problem, but I can see I manage to fix it!

**Comment by sandrina-p** [comment]
@kaisermann sure! You can see it [on this project commit](https://github.com/sandrina-p/s008080_2019/commit/8c49d40e8a8ea50e63cb9cb4cb908e1682c96a0d#diff-268458b2394d4416a6325a1c2aab8591R134-R137) (the next commit reverts the error).

And actually I think I know why it didn't work! It's because I installed `svelte-loadable` as a dependency instead of devDependency! I tried right now to install it as `devDependency` and it worked! It's something that could be improved on README, clarify to install it as devDep. :)

**Comment by kaisermann** [comment]
I'm going to take a look at it when I get some free time. And it should be a common dep 😱! It's going to be used in the final code that runs on the browser. 🤔🤔🤔
