### ISSUE TITLE
Allow to fill "success" slot

### ISSUE THREAD

**Issue by kaisermann** [kaisermann/svelte-loadable#2]
Maybe it'd be interesting to allow to customize the `success` slot instead of just rendering the dynamic component

```html
<Loadable {loader} bind:component>
	<div slot="success">
		<svelte:component this={component} customProps={props}/>
	</div>
</Loadable>
```

**Comment by EmilTholin** [comment]
That would be cool. Just make sure not to run into [this annoying behavior](https://github.com/EmilTholin/svelte-routing/issues/1).

**Comment by kaisermann** [comment]
I think svelte handles this case (at least the basic one) for us because `component` start as null and will not be instantiated (I could be wrong though...) 🤔
