### ISSUE TITLE
Understanding how it can work

### ISSUE THREAD

**Issue by mfrachet** [kaisermann/svelte-loadable#3]
Hi,

Thank you for the module 😊 . I know that it's not that much about an issue but I'm really curious to understand how the module work internally.

I try to read the code but I'm stuck with the `loader` thing that seems to execute something that looks like `() => import('component-patch')` but is this `import` coming from webpack or is it the native one (polyfilled)?

Do you think this approach can work in an app that relies on rollup or parcel?

Thank you again for this package 👍

**Comment by EmilTholin** [comment]
Hi @mfrachet!

`import()` is called [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Import) and is a stage 3 proposal, but it's supported by [Webpack](https://webpack.js.org/guides/code-splitting/#dynamic-imports), [Rollup](https://rollupjs.org/guide/en#dynamic-import) and [Parcel](https://parceljs.org/code_splitting.html#using-dynamic-imports).

**Comment by mfrachet** [comment]
Ooh ! It's super cool! We actually don't have to care about the bundler and simply to rely on the thing 😮 

Thanks for your answer, I'm going to study the thing!
