### ISSUE TITLE
Load over HTTP?

### ISSUE THREAD

**Issue by tmclane** [kaisermann/svelte-loadable#31]
Can a svelte component be loaded from an HTTP endpoint?

**Comment by kaisermann** [comment]
@tmclane Yes, but it depends on what a `svelte component` means. Is it pre-compiled or a raw `.svelte` file? For the first option you'd just need to pass a promise to the `Loadable` component which resolves to a compiled component. For the latter, you'd need to have the compiler in the browser context, as the REPL does.
