### ISSUE TITLE
Programatically define inset point 

### ISSUE THREAD

**Issue by daslicht** [kaisermann/svelte-loadable#32]
Hi,
is it possible to load component without first defining the ```<Loadable```/>

eg load component and then simply insert somewhere decided at runtime.

**Comment by kaisermann** [comment]
Hey @daslicht 👋

Yeah, it's possible. You wouldn't even need this component. Check the `svelte:component` special tag in svelte's doc: https://svelte.dev/docs#svelte_component (`svelte-loadable` uses it behind the scenes)

**Comment by daslicht** [comment]
Thank you !
