### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by ItalyPaleAle** [kaisermann/svelte-loadable#5]
Thanks for building this!

I noticed however that the repository is missing a license. Even though there's a `"license": "MIT"` inside the package.json, that is not really a way to license your source code.

To avoid legal troubles for projects adopting your code, any chance you could add a LICENSE file into the repo?

(Remember that "no license" = "all rights reserved" by default 😢)

**Comment by kaisermann** [comment]
Oh, my bad! I have already added the license file to the repo. I'll update the package as soon as I can 👌

Thanks for bringing this to my attention!

**Comment by ItalyPaleAle** [comment]
Thank you very much!
