### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by s0kil** [kaisermann/svelte-loadable#7]
When using as: `import Loadable from "svelte-loadable";`
I get this error:
```bash
node_modules/svelte-loadable/Loadable.svelte:1
<script>
^

SyntaxError: Unexpected token <
```

But the component works as expected with importing: `import Loadable from "svelte-loadable/Loadable.svelte";`

**Comment by EmilTholin** [comment]
Hi @s0kil!

It's hard to say what might be wrong without a minimal reproducible example. Please create one that we can clone and ideally do `npm install && npm start` to try.

**Comment by s0kil** [comment]
@EmilTholin 
I tried to reproduce in an example: https://codesandbox.io/s/svelte-loadable-b7s3t
It seems like this error is project specific.

**Comment by EmilTholin** [comment]
Right, that's why it would be very beneficial if you could create a minimal reproducible example in a GitHub repository with the setup you are using that gives rise to the error.

**Comment by mvanhalen** [comment]
I have seen this to. It works in the REPL environment, but downloading the zip of that same code does not work work in Visual Studio Code.
Here is my sample from REPL https://svelte.dev/repl/f300b31ad42f49539a80e707b434ff43?version=3.6.1
Here a npm build version on Azure Storage blob with the error https://igtemplate.blob.core.windows.net/public/packages/svelte/public/index.html
And here a zip file which has the issue https://1drv.ms/u/s!AhkkN-xT7UA5jMRH1MHhj4wpqOdl_g
Also when doing npm run start. I think it´s some config thing actually but I did not find what exactly.

**Comment by kaisermann** [comment]
This seems to me to be an issue with your build step. @mvanhalen I just cloned your repo, installed it and everything seems to be working fine

![image](https://user-images.githubusercontent.com/12702016/64290688-f102f100-cf3c-11e9-80e6-df60b18f8347.png)
